image: ghcr.io/vioneta/{arch}-vionetaos
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-homeassistant-base:2024.06.1
  armhf: ghcr.io/home-assistant/armhf-homeassistant-base:2024.06.1
  armv7: ghcr.io/home-assistant/armv7-homeassistant-base:2024.06.1
  amd64: ghcr.io/home-assistant/amd64-homeassistant-base:2024.06.1
  i386: ghcr.io/home-assistant/i386-homeassistant-base:2024.06.1
# codenotary:
#   signer: notary@home-assistant.io
#   base_image: notary@home-assistant.io
# cosign:
#   base_identity: https://github.com/home-assistant/docker/.*
#   identity: https://github.com/home-assistant/core/.*
labels:
  io.hass.type: core
  org.opencontainers.image.title: Vioneta Agro
  org.opencontainers.image.description: Smart agriculture platform running on Python 3
  org.opencontainers.image.source: https://github.com/Vioneta/core
  org.opencontainers.image.authors: The Vioneta Authors
  org.opencontainers.image.url: https://www.vioneta.com/
  org.opencontainers.image.documentation: https://www.vioneta.com/docs/
  org.opencontainers.image.licenses: Apache License 2.0
